name: Events demo
on: 
    push:
        branches:
            - main
        paths: 
            - '.github/workflows/o2*.yml'
jobs: 
    events-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: print greeting
              run: echo hello
