name: Events demo
on: 
    push:
        branches:
            - main
        paths: 
            - '.github/workflows/02*.yml'
jobs: 
    events-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: print greeting
              run: echo hello
            - name: Output eveny data
              run: echo "${{toJSON(github.event)}}"
            - name: Getting code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test:envTest
            - name: Build application
              run: npm run build