name: Events demo
on: 
    push:
        branches:
            - main
        paths: 
            - '.github/workflows/02*.yml'
jobs: 
    events-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: print greeting
              run: echo hello
            - name: Output eveny data
              run: echo "${{toJSON(github.event)}}"